name: Test Doctests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

      steps:
        - uses: actions/checkout@v2
        - name: Install dependecies
          uses: VaultVulp/action-pipenv@v2.0.1
          with:
            command: install -d # Install all dependencies, including development ones
        - name: Test Doctests with Pytest
          run: pytest inquisitor/question.py --doctest-modules
